### ISSUE TITLE
Bulk inserts/updates

### ISSUE THREAD

**Issue by Proximator** [kostaskougios/mapperdao#9]
I tried to do a bulk insert of entities, and when I turn on the logging, I discovered that the ordering is not very efficient. 
In fact, suppose I have an entity ProductEntity that have a one to many relation ProductAttribute.
In the logs, I can see insert p1, then batch for a11, a12, .., insert p2, then batch a21, a22,...
Is there a way like in hibernate to reoder the inserts   
hibernate.order_inserts=true and hibernate.order_updates=true.
 ?
ie. having batch insert p1, p2, p3, .... then batch insert a11, a12,....a21, a22, ....

**Comment by kostaskougios** [comment]
Hi, it could be done but currently I am not maintaining the lib (maybe I will resume at a later time). Is it making the updates a lot slower for you? (times?)

**Comment by Proximator** [comment]
Yes, it is 3 times slower if I did it in JDBC with this order but obviously it is more verbose code !
I tried to use slick instead of mapperdao, but it is low level and even worse in term of performance for this scenario, that's why I am looking for a solution with mapperdao.

**Comment by kostaskougios** [comment]
I actually happen to use slick as well (3.2 at this moment) and indeed it sends the batches in a similar way you describe above (I was forced to manually group the batches together and then send them to slick). 

Slick gives you a lot more control but it is indeed quite more complex to do the things that an ORM does for you.

Reg. mapperdao, unfortunately the lib (though it is quite good and useful in my opinion) didn't become popular and currently I have it in slight maintenance mode, i.e. provide artifacts for new scala versions.

Are you sure though you pass the entities to mapper dao as 1 big Seq ? Looking at the code 

https://github.com/kostaskougios/mapperdao/blob/master/src/main/scala/com/googlecode/mapperdao/updatephase/prioritise/PriorityPhase.scala

it seems it should send the big batches as you want them. Can you paste your code here?

**Comment by Proximator** [comment]
Below some part of the code :
`
val products = List(p1, p2, p3,.....)
mapperDao.insertBatch(UpdateConfig.default, ProductEntity, products)
`

`
object ProductEntity extends Entity[Int, NaturalIntId, Product]("Products"){
val id = key("productid") to (_.getId)
val active = column("active") to (_.isActive)
.......
val attributes = manytomany(AttributeEntity) join("ProductAttributes", "productid", "attributeid") tojava (_.getAttributes)
val categories = manytomany(CategoryEntity) join("ProductCategories", "productid", "categoryid") tojava (_.getCategories)
val prices= manytomany(CategoryEntity) join("ProductPrices", "productid", "priceid") tojava (_.getCategories)
......
} 
`

**Comment by kostaskougios** [comment]
Hi,

I run 2 test suites, one with autogenerated keys and one with the keys provided to mapperdao. Both execute the batches correctly and as you would like them in your original example:

[ScalaTest-run-running-ManyToManyAutoGeneratedSuite] DEBUG c.g.m.jdbc.Jdbc - batchUpdate
----------------- start of batch -------------------------------------
insert into Product(name) values('blue jean')
insert into Product(name) values('green jean')
----------------- end of batch ---------------------------------------
[ScalaTest-run-running-ManyToManyAutoGeneratedSuite] DEBUG c.g.m.jdbc.Jdbc - batchUpdate
----------------- start of batch -------------------------------------
insert into Attribute(name,value) values('colour','blue')
insert into Attribute(name,value) values('size','medium')
insert into Attribute(name,value) values('colour','green')
insert into Attribute(name,value) values('size','small')
----------------- end of batch ---------------------------------------
[ScalaTest-run-running-ManyToManyAutoGeneratedSuite] DEBUG c.g.m.jdbc.Jdbc - batchUpdate
----------------- start of batch -------------------------------------
insert into Product_Attribute(product_id,attribute_id) values(1,1)
insert into Product_Attribute(product_id,attribute_id) values(1,2)
insert into Product_Attribute(product_id,attribute_id) values(2,3)
insert into Product_Attribute(product_id,attribute_id) values(2,4)
----------------- end of batch ---------------------------------------

So I can't tell why it is not working for you. With the code you provided above, you should get similar batch executions.

**Comment by kostaskougios** [comment]
Can you provide a small sample program that I can run standalone?
